### ISSUE TITLE
can you answer me some questions?

### ISSUE THREAD

**Issue by joycesmith** [UP-RS-ESP/Normalize#1]
IS your code used Z-score standardization? 
Where is your dataset that should be standardized?
I'm looking forward to your reply as soon as possible, thanks!

**Comment by Rheinwalt** [comment]
We used this code on different datasets. Are you referring to the data from the figure? That would be synthetic. Have a look at [visual.py](https://github.com/UP-RS-ESP/Normalize/blob/master/visual.py).

The code does not perform a z-score transformation to the sample mean. It estimates for each value in a time series the quantile and translates these quantiles with the [Probit function](https://en.wikipedia.org/wiki/Probit) to the corresponding values of the normal distribution N(0,1). The transformation basically preserves the rank order while ensuring that the new time series is normally distributed.
